Repository ros-visualization/rqt_reconfigure, pull requests merged in 2020-06, with the labels that each got.

#84 fix shebang line for python3 support
  CMakeLists.txt
Labels: bug

#81 Fixed package to run with ros2 run
  scripts/rqt_reconfigure
  setup.cfg
  setup.py
  src/rqt_reconfigure/main.py
Labels: bug

#80 Handle invalid enum values
  src/rqt_reconfigure/param_editors.py
Labels: bug

#76 Only enable apply group button when effective
  src/rqt_reconfigure/param_groups.py
Labels: enhancement

#79 Save instance state in rqt settings
  src/rqt_reconfigure/node_selector_widget.py
  src/rqt_reconfigure/param_widget.py
  src/rqt_reconfigure/paramedit_widget.py
  src/rqt_reconfigure/text_filter_widget.py
Labels: enhancement

#85 Support PEP 338 invocation of rqt_reconfigure
  setup.py
  src/rqt_reconfigure/__main__.py
Labels: enhancement

#86 Support PEP 338 invocation of rqt_reconfigure
  scripts/rqt_reconfigure
  src/rqt_reconfigure/__main__.py
Labels: enhancement, port
